---

- name: "Prepare"
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: "Ensure apt cache is fresh"
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 0
      when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'
