---
- name: "Converge (no_service)"
  hosts: all
  gather_facts: true
  become: true

  pre_tasks:
    - name: "Install python3 and apt (required for Ansible modules)"
      ansible.builtin.raw: |
        apt update && apt install --no-install-recommends -y python3 python3-apt
      changed_when: true

  roles:
    - role: ../
      vars:
        # Disable service management for this scenario
        ansible_role_template_manage_service: false
